# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'PixleeSDK', :path => "../"


  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end
