source 'https://github.com/CocoaPods/Specs.git'

target 'pixlee-ios-sdk', :exclusive => true do
  pod "pixlee-ios-sdk", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "pixlee-ios-sdk", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
