version: 2.1
executors:
  default:
    docker:
      - image: cimg/base:2020.01
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - refresh-documentation:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - set-directory
      - add-pixlee-credentials
      - fastlane_preparation
      - ui-tests
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  deploy:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - set-directory
      - deploy-cooapods
  refresh-documentation:
    executor: default
    steps:
      - deploy:
          name: Refresh eng-docs
          command: |
            curl --user ${CIRCLECI_ENG_DOCS_PROJECT_API_TOKEN}: \
              --data 'build_parameters[CIRCLE_JOB]=build-deploy' \
              https://circleci.com/api/v1.1/project/github/pixlee/eng-docs/tree/master

commands:
  set-directory:
    steps:
      - run:
          name: Install CocoaPods + set directory
          command: pod install --project-directory=Example
  add-pixlee-credentials:
    steps:
      - run:
          name: add pixlee credentials
          command: |
            echo $PIXLEE_CREDENTIALS | base64 --decode > Example/Example/PixleeCredentials.plist
            ls -al Example/Example
  fastlane_preparation:
    steps:
      - run: bundle update fastlane
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  ui-tests:
    steps:
      - run:
          name: UI tests using Fastlane
          command: bundle exe fastlane test

  deploy-cooapods:
    steps:
      - run:
          name: deploy cooapods
          command: |
            pod lib lint --allow-warnings
            pod trunk push --allow-warnings
