version: 2.1
executors:
  default:
    docker:
      - image: cimg/base:2020.01
workflows:
  test-deploy:
    jobs:
      - test-spm:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test-cocoapods:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test-carthage:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - test-carthage
            - test-spm
            - test-cocoapods
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - refresh-documentation:
          requires:
            - test-carthage
            - test-spm
            - test-cocoapods
          filters:
            branches:
              only: master
jobs:
  test-spm:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - add-pixlee-credentials
      - fastlane_preparation
      - spm-ui-tests
  test-cocoapods:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - add-pixlee-credentials
      - fastlane_preparation
      - download-cocoapods-dependencies
      - cocoapods-ui-tests
  test-carthage:
    macos:
      xcode: 13.2.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - add-pixlee-credentials
      - fastlane_preparation
#      - download-carthage-dependencies
      - carthage-ui-tests
  deploy:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - download-carthage-dependencies
#      - download-cocoapods-dependencies
      - deploy-cooapods
  refresh-documentation:
    executor: default
    steps:
      - deploy:
          name: Refresh eng-docs
          command: |
            curl --user ${CIRCLECI_ENG_DOCS_PROJECT_API_TOKEN}: \
              --data 'build_parameters[CIRCLE_JOB]=build-deploy' \
              https://circleci.com/api/v1.1/project/github/pixlee/eng-docs/tree/master

commands:
  download-cocoapods-dependencies:
    steps:
      - run:
          name: Install CocoaPods dependencies
          command: pod install --project-directory=Example
  download-carthage-dependencies:
    steps:
      - run:
          name: Install Carthage dependencies
          command: ./bin/setup
  add-pixlee-credentials:
    steps:
      - run:
          name: add pixlee credentials
          command: |
            echo $PIXLEE_CREDENTIALS | base64 --decode > Example/Example/PixleeCredentials.plist
            ls -al Example/Example
  fastlane_preparation:
    steps:
      - run: bundle update fastlane
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  carthage-ui-tests:
    steps:
      - run:
          name: Carthage SDK UI tests
          command: bundle exe fastlane carthage_sdk_test
  cocoapods-ui-tests:
    steps:
      - run:
          name: Cocoapods SDK UI tests
          command: bundle exe fastlane cocoapods_sdk_test
  spm-ui-tests:
    steps:
      - run:
          name: SPM SDK UI tests
          command: bundle exe fastlane spm_sdk_test
  deploy-cooapods:
    steps:
      - run:
          name: deploy cooapods
          command: |
            pod lib lint --allow-warnings
            pod trunk push --allow-warnings
