# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of before_all do"
  before_all do
    setup_circle_ci
  end
  
  lane :test do
    run_tests(workspace: "Example/Example.xcworkspace",
                devices: ["iPhone 8"],
                scheme: "ExampleUITests")
    end
end



