# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Testing SDK's demo project to make sure PixleeSDK has no erros."
  before_all do
    setup_circle_ci
  end
  
  # lane :test do
  #   # desc "Test ExamplePod"
  #   # run_tests(project: "Example/ExamplePod.xcworkspace",
  #   #   devices: ["iPhone 13 Pro"],
  #   #   scheme: "ExampleUITests")
    
  #   run_tests(
  #     project: 'Example/Example.xcodeproj',
  #     devices: ["iPhone 13 Pro"],
  #     scheme: "ExampleUITests")
  # end
  
  # lane :screenshots do
  #   # desc "Screenshot ExamplePod"
  #   # capture_screenshots(project: "Example/ExamplePod.xcworkspace",
  #   #   scheme: "UITests",
  #   #   sdk: "iphonesimulator")

  #   capture_screenshots(project: "Example/Example.xcodeproj",
  #                       scheme: "UITests",
  #                       sdk: "iphonesimulator")
  # end

  lane :spm_sdk do
    desc "Test Swift Package Manager"
      run_tests(
        project: 'Example/Example.xcodeproj',
        devices: ["iPhone 13 Pro"],
        scheme: "ExampleUITests")
    
    desc "Screenshot Swift Package Manager"
      capture_screenshots(project: "Example/Example.xcodeproj",
                          scheme: "UITests",
                          sdk: "iphonesimulator")
  end

  lane :cocoapods_sdk do
    desc "Test Cocoapods"
    run_tests(
      workspace: 'Example/ExamplePod.xcworkspace',
      devices: ["iPhone 13 Pro"],
      scheme: "ExampleUITests")

    desc "Screenshot Cocoapods"
    capture_screenshots(workspace: "Example/ExamplePod.xcworkspace",
                        scheme: "UITests",
                        sdk: "iphonesimulator")
  end

  lane :test_all_sdks do
    cocoapods_sdk
    spm_sdk
  end

end



