source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'pixlee-ios-sdk' do
  pod "pixlee-ios-sdk", :path => "../"
end

target 'Tests' do
  pod "pixlee-ios-sdk", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
